### ISSUE TITLE
Set up Codecov environment variable for coverage reporting

### ISSUE THREAD

**Issue by rask24** [rask24/minishell#1]
## Description
- Enable automatic coverage reporting for the project
- Integrate Codecov with our GitHub workflow

## Tasks
- [x] Generate a Codecov token from the Codecov website
- [x] Add the Codecov token as a secret in our GitHub repository
- [x] Update our GitHub Actions workflow to use the Codecov token
