### ISSUE TITLE
Apply expansion

### ISSUE THREAD

**Issue by rask24** [rask24/minishell#110]
### TODO

- [x] Introduce expansion to exec
- [x] Apply quote removal to a delimiter of here document
- [x] Apply expansion to a file name of redirection
- [x] Apply expansion to contents of here document

**Comment by rask24** [comment]
## memo

``` c
void	  handle_heredoc(const char *delimiter, t_redirect_info *info)
```
