### ISSUE TITLE
Input such as `''`, `""` displays unappropriate err msg

### ISSUE THREAD

**Issue by alex216** [rask24/minishell#131]
```bash
minishell$ ''
minishell: /Users/yliu/.pyenv/shims/: Is a directory
minishell$ ""
minishell: /Users/yliu/.pyenv/shims/: Is a directory
```

**Comment by rask24** [comment]
## TODO

- [ ] Fix input "" and ''
- [ ] Fix input . and ..
- [ ] Fix execute empty string
