### ISSUE TITLE
Refactor exec module

### ISSUE THREAD

**Issue by rask24** [rask24/minishell#137]
## TODO

- [x] Move exec logic to main
- [x] Rename exec_command_internal to exec_external_command
- [x] Export execute_ast_node only
- [x] Optimize redundant argument `conf`
- [x] Rename `wait_for_children` to `wait_children`
