### ISSUE TITLE
Init ui module

### ISSUE THREAD

**Issue by rask24** [rask24/minishell#15]
## TODO
- [x] Implement signal handler setup function
- [x] Implement signal handler reset function
- [x] Implement function to save terminal settings
- [x] Implement function to restore terminal settings
- [x] Implement temporary command execution using `/bin/sh -c`

**Comment by rask24** [comment]
[BUG]
```shell
minishell$ cat
^C
minishell$ minishell$
```
