### ISSUE TITLE
Init parser module

### ISSUE THREAD

**Issue by rask24** [rask24/minishell#25]
## TODO

- [x] Implement `parser`
- [x] Implement `parse_simple_command`
- [x] ~Implement `parse_pipe`~  in #44

**Comment by rask24** [comment]
- [ ] Add test: syntax error
