### ISSUE TITLE
Implement `parse_command`

### ISSUE THREAD

**Issue by rask24** [rask24/minishell#64]
## TODO

- [x] Update `grammer.md`
- [x] Implement `parse_command`
- [x] Test `parse_command`
- [x] Replace `handle_error` with `handle_syntax_error`

### grammer

```bison
 pipeline         :              command
                  | pipeline '|' command
                  ;
 command          : simple_command
                  | '(' list ')'
                  | '(' list ')' redirect_list
                  ;
```
