### ISSUE TITLE
Implement `exec_and_or`

### ISSUE THREAD

**Issue by rask24** [rask24/minishell#93]
## TODO

- [x] ~fix `test_parse_list`~
- [x] f~ix `parse_list`~
- [x] implement `exec_and_or`
- [x] add e2e tests
